package com.example.finalproject_breathe_again.ui.craving.story

import com.example.finalproject_breathe_again.R

object DataStory {
    fun generateStoryList(): List<Story> {
        val defaultImageUrl = R.drawable.ic_stories
        val story = mutableListOf<Story>()

        story.add(
            Story.Builder()
                .id("1")
                .title("Overcoming the First Week")
                .overview("I used to believe I couldn't survive a single day without smoking. When I finally quit, the first week felt like torture. Every craving was a battle. But by day seven, I noticed something incredible—I could breathe easier. That small victory gave me hope. It's now been three years, and I feel like a completely new person.")
                .date("05/02/2025")
                .imageUrl(defaultImageUrl.toString())
                .author("John D.")
                .build()
        )

        story.add(
            Story.Builder()
                .id("2")
                .title("A Promise to My Daughter")
                .overview("I quit smoking for my daughter. She begged me to stop after she learned in school about how harmful smoking is. She said, 'Mommy, I don't want you to get sick.' That broke my heart. Every time I felt the urge, I thought about her big brown eyes and her future. Now, a year later, I have more energy to play with her, and the smell of smoke no longer clings to her clothes.")
                .date("06/12/2025")
                .imageUrl(defaultImageUrl.toString())
                .author("Anna M.")
                .build()
        )

        story.add(
            Story.Builder()
                .id("3")
                .title("My Best Friend and My Biggest Cheerleader")
                .overview("My best friend supported me every step of the way. Every time I wanted to give up, she reminded me why I started this journey. She even threw me a '100 Days Smoke-Free' party. Having someone believe in me made all the difference.")
                .date("10/01/2025")
                .imageUrl(defaultImageUrl.toString())
                .author("Sophia R.")
                .build()
        )

        story.add(
            Story.Builder()
                .id("4")
                .title("Finding Strength in Exercise")
                .overview("Quitting smoking left me feeling restless, so I took up running. At first, I could barely make it around the block. But day by day, my stamina grew. Now, I’ve completed three 5Ks, and I’ve never felt more alive.")
                .date("20/03/2025")
                .imageUrl(defaultImageUrl.toString())
                .author("Michael B.")
                .build()
        )

        story.add(
            Story.Builder()
                .id("5")
                .title("Becoming a Role Model")
                .overview("When my younger brother saw me quit smoking, he decided to quit as well. It feels amazing to know that my decision inspired someone else to live a healthier life. Together, we’ve built a stronger bond, free from cigarettes.")
                .date("15/04/2025")
                .imageUrl(defaultImageUrl.toString())
                .author("James K.")
                .build()
        )

        story.add(
            Story.Builder()
                .id("6")
                .title("One Day at a Time")
                .overview("Every morning, I tell myself, 'Just for today, I won’t smoke.' Breaking the journey into small, manageable steps made it less overwhelming. Now, those small steps have added up to over a year of being smoke-free!")
                .date("01/02/2025")
                .imageUrl(defaultImageUrl.toString())
                .author("Emily W.")
                .build()
        )

        story.add(
            Story.Builder()
                .id("7")
                .title("Reclaiming My Health")
                .overview("The best reward of quitting smoking has been the improvement in my health. I no longer wake up coughing, my energy levels have skyrocketed, and my skin has cleared up. It’s like I’ve been given a new lease on life.")
                .date("12/09/2025")
                .imageUrl(defaultImageUrl.toString())
                .author("Olivia T.")
                .build()
        )

        story.add(
            Story.Builder()
                .id("8")
                .title("Support from an Online Community")
                .overview("Joining an online community of ex-smokers was a game-changer for me. Sharing my struggles and victories with people who truly understood made me feel less alone. Their encouragement kept me going on tough days.")
                .date("18/06/2025")
                .imageUrl(defaultImageUrl.toString())
                .author("David L.")
                .build()
        )
        story.add(
            Story.Builder()
                .id("9")
                .title("Breathing Fresh Air")
                .overview("I never realized how much I took fresh air for granted until I quit smoking. Now, every deep breath feels like a gift, and I’m grateful for the strength to quit.")
                .date("25/04/2025")
                .imageUrl(defaultImageUrl.toString())
                .author("Olivia Martinez")
                .build()
        )
        story.add(
            Story.Builder()
                .id("10")
                .title("Overcoming the Social Pressure")
                .overview("Smoking was a habit I picked up to fit in with friends. Quitting meant standing out, but it also meant standing up for myself. It’s been a year now, and I’m proud of the decision I made.")
                .date("10/04/2025")
                .imageUrl(defaultImageUrl.toString())
                .author("Liam Robinson")
                .build()
        )
        story.add(
            Story.Builder()
                .id("11")
                .title("Healthier Holidays")
                .overview("Holidays were always filled with stress and smoke. Quitting gave me the opportunity to truly relax and enjoy time with family. It’s a new tradition I’m excited to continue.")
                .date("20/03/2025")
                .imageUrl(defaultImageUrl.toString())
                .author("Sophia Harris")
                .build()
        )
        story.add(
            Story.Builder()
                .id("12")
                .title("From Stress to Success")
                .overview("I used to smoke to cope with stress. Quitting taught me healthier ways to manage it, like meditation and exercise. Now, I’m healthier and happier than ever.")
                .date("10/02/2025")
                .imageUrl(defaultImageUrl.toString())
                .author("Noah Clark")
                .build()
        )
        story.add(
            Story.Builder()
                .id("13")
                .title("A Better Role Model")
                .overview("As a teacher, I wanted to be a better role model for my students. Quitting smoking showed them that it’s possible to make positive changes, no matter how hard it seems.")
                .date("01/01/2025")
                .imageUrl(defaultImageUrl.toString())
                .author("Ava Perez")
                .build()
        )
        story.add(
            Story.Builder()
                .id("14")
                .title("Rediscovering Joy")
                .overview("Quitting smoking gave me a new lease on life. Food tastes better, my sense of smell has returned, and I’ve rediscovered the simple joys of life.")
                .date("25/12/2024")
                .imageUrl(defaultImageUrl.toString())
                .author("Isabella Davis")
                .build()
        )
        story.add(
            Story.Builder()
                .id("15")
                .title("Saving for the Future")
                .overview("Quitting smoking not only improved my health but also my finances. The money I’ve saved has gone towards a family vacation we’ve always dreamed of.")
                .date("10/12/2024")
                .imageUrl(defaultImageUrl.toString())
                .author("Mason Walker")
                .build()
        )
        story.add(
            Story.Builder()
                .id("16")
                .title("Turning Challenges into Opportunities")
                .overview("Every craving was a challenge, but it was also an opportunity to grow stronger. Quitting smoking taught me resilience and determination.")
                .date("01/11/2024")
                .imageUrl(defaultImageUrl.toString())
                .author("Elijah King")
                .build()
        )
        story.add(
            Story.Builder()
                .id("17")
                .title("The Power of Mindfulness")
                .overview("Practicing mindfulness helped me overcome cravings. Focusing on my breath and staying present reminded me of my goals and kept me on track.")
                .date("15/10/2024")
                .imageUrl(defaultImageUrl.toString())
                .author("Mila Scott")
                .build()
        )
        story.add(
            Story.Builder()
                .id("18")
                .title("A Second Chance")
                .overview("After a health scare, I knew I had to quit smoking. It wasn’t easy, but it was worth it. Now, I have a second chance at life, and I’m making the most of it.")
                .date("01/09/2024")
                .imageUrl(defaultImageUrl.toString())
                .author("Ethan Lewis")
                .build()
        )
        story.add(
            Story.Builder()
                .id("19")
                .title("Living Without Limits")
                .overview("Quitting smoking removed the limits I didn’t even realize were there. I can run, play with my kids, and enjoy life without feeling out of breath.")
                .date("15/08/2024")
                .imageUrl(defaultImageUrl.toString())
                .author("Charlotte Hill")
                .build()
        )
        story.add(
        Story.Builder()
            .id("20")
            .title("Celebrating Every Milestone")
            .overview("Every smoke-free day is a milestone worth celebrating. Quitting taught me to appreciate the small victories and find joy in the journey.")
            .date("01/07/2024")
            .imageUrl(defaultImageUrl.toString())
            .author("Jack Hall")
            .build()
        )

        return story
    }
}

